FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD FlowQuest.jar /opt/FlowQuest/
EXPOSE 8080
WORKDIR /opt/FlowQuest/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "FlowQuest.jar"]
