version: '3'
services:
  flowquest-db:
    build: .
    container_name: flowquest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flowquest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
